server:
  port: 8080
spring:
  application:
    name: "crudCleanArchitectureImperactive"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    #CONEXIÓN MYSQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clean_architecture
    username: root
    password:
    #propiedades hibernate MYSQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

      #CONEXIÓN H2
      #datasource:
      #  url: "jdbc:h2:mem:test"
      #  username: "sa"
      #  password: "pass"
      #  driverClassName: "org.h2.Driver"

      #propiedades hibernate H2
    # jpa:
    #    databasePlatform: "org.hibernate.dialect.H2Dialect"
